### ISSUE TITLE
Call for user update every 45min 

### ISSUE THREAD

**Issue by hkd987** [cedpoilly/vue-gapi#10]
Google expires the user token after one hour the recommended way to keep the user logged in is to refresh the token after 45min.

We should explore a way to keep the user logged in if the browser is still open. This will create a seamless user experience.

**Comment by hkd987** [comment]
https://developers.google.com/identity/sign-in/web/listeners

See refresh method.

**Comment by hkd987** [comment]
` refreshToken (event) {
    const GoogleUser = this.authInstance.currentUser.get()
    GoogleUser.reloadAuthResponse()
      .then((authResult) => {
        localStorage.setItem('access_token', authResult.access_token)
        localStorage.setItem('id_token', authResult.id_token)
        localStorage.setItem('expires_at', this._expiresAt(authResult))
        })
      })
  }`


This should update the auth_token etc... I had to pull the expiresAt into its own private method to keep the code clean. 

`  // NOTE: handle expiresAt method
  _expiresAt = (authResult) => {
    return JSON.stringify(authResult.expires_in * 1000 + new Date().getTime())
  }`

Ill see about a pull request on this soon but haven't had time to write test.

**Comment by hkd987** [comment]
https://github.com/cedpoilly/vue-gapi/pull/11

See pull request

**Comment by cedpoilly** [comment]
Version 0.0.10 is now on npm and inlcudes the code for PR #11
