### ISSUE TITLE
Update Config on Fly

### ISSUE THREAD

**Issue by annettaws** [cedpoilly/vue-gapi#2]
Hi,
I'm trying to use your Vue wrapper.
First I change your code to get the Google Config from the server, so i can change the config, save them and "re-init" each time my gapi.client.
It work.

Now I would like to understand how can I initialize the "googleAuthService.authInstance", because after calling the  gapi.client.init it is always null!
what i'm doing wrong?
thanks

**Comment by cedpoilly** [comment]
Hi @annettaws
I might need to see your code to help with that. You can provide it here or contact me via email

**Comment by cedpoilly** [comment]
@annettaws please check the latest version, should work fine now.

**Comment by annettaws** [comment]
Hi Ced,
i'll check the new versions. 
Anyway below is the code modified by me:

`var googleAuthService = new GoogleAuthService();
var login = googleAuthService.login;
var logout = googleAuthService.logout;
var isAuthenticated = googleAuthService.isAuthenticated;
var getUserData = googleAuthService.getUserData;
var staticConfig = {};

var VueGAPI = {
  install: function (Vue, clientConfig) {
    Vue.gapiLoadClientPromise = null;
    staticConfig = clientConfig

    var resolveAuth2Client = function (resolve, reject, dynamicConfig = staticConfig) {
      if (!gapi.auth) {
        gapi.load('client:auth2', function () {
          Vue.gapiLoadClientPromise = gapi.client.init(dynamicConfig)
            .then(function () {
              console.info('gapi client initialised.');
              googleAuthService.authInstance = gapi.auth2.getAuthInstance();
              resolve(gapi);
            });
        });
      } else {
        resolve(gapi);
      }
    };

    Vue.prototype.$getGapiClient = function (dynamicConfig = staticConfig) {
      return new Promise(function (resolve, reject) {
        if (Vue.gapiLoadClientPromise &&
            Vue.gapiLoadClientPromise.status === 0) { // promise is being executed
          resolve(Vue.gapiLoadClientPromise);
        } else {
          resolveAuth2Client(resolve, reject, dynamicConfig);
        }
      })
    };`

Then on my component i'll do this:

`testConnection: function testConnection() {
            var vm = this;
            var config = {
                'apiKey': vm.gSettings.apiKey,
                'clientId': vm.gSettings.clientId,
                'discoveryDocs': vm.gSettings.discoveryDocs,
                'scope': vm.gSettings.scope
            };
            if (this.$isAuthenticated()) {
                this.$logout(config).then(this.$getGapiClient(config).then(function () {
                    vm.$events.fire('show-snack', { closing: true,
                        text: 'Google Connected Successfully',
                        color: 'success' });
                }, function (err) {
                    vm.$events.fire('show-snack', { closing: true,
                        text: 'Error: ' + err.message,
                        color: 'error', timeout: -1 });
                }));
            } else {
                this.$getGapiClient(config).then(function () {
                    vm.$events.fire('show-snack', { closing: true,
                        text: 'Google Connected Successfully',
                        color: 'success' });
                }, function (err) {
                    vm.$events.fire('show-snack', { closing: true,
                        text: 'Error: ' + err.message,
                        color: 'error', timeout: -1 });
                });
            }
        }`
