### ISSUE TITLE
Vue CLI 3 Plugin

### ISSUE THREAD

**Issue by hkd987** [cedpoilly/vue-gapi#22]
Work toward creating a fork // or move to Vue 3 Plugin 

https://cli.vuejs.org/dev-guide/plugin-dev.html#distributing-the-plugin

**Comment by nidkil** [comment]
I have this setup and working for another plugin project, so it should be fairly straight forward for me to set this up for vue-gapi.

**Comment by cedpoilly** [comment]
Kindly create a PR for it. 🙂
