### ISSUE TITLE
v0.1.0 isn't available on npm

### ISSUE THREAD

**Issue by cweave** [cedpoilly/vue-gapi#33]

**Comment by sadortun** [comment]
@cedpoilly  Can you update  NPM package please ?

Thanks,
Samuel

**Comment by cedpoilly** [comment]
Hi @cweave @sadortun

I've just **published** it.
Seems like the version number is still not updated on npmjs.com, but **v0.1.0** is **available** now. Kindly check. 

Thanks ✌🏼

**Comment by cedpoilly** [comment]
Package is updated on npm.
