### ISSUE TITLE
vue-gapi.common.js?15fd:328 Uncaught (in promise) TypeError: res is not a function

### ISSUE THREAD

**Issue by everttrollip** [cedpoilly/vue-gapi#38]
### Description

* Use the latest vue-gapi npm package (^0.1.0)
* Call the Vue prototype login function (Vue.prototype.$login())
* See error in developers console: 

> vue-gapi.common.js?15fd:328 Uncaught (in promise) TypeError: res is not a function
    at eval (vue-gapi.common.js?15fd:328)

**Comment by cedpoilly** [comment]
Hi @everttrollip 
Was it the case in the previous version or is it specific to `0.1.0`?

**Comment by everttrollip** [comment]
@cedpoilly specific to 0.1.0. Didn't have the same issue in previous version. Seems to be a callback function that needs to be sent with the login function? Why? Or am I misunderstanding?

**Comment by everttrollip** [comment]
Hi @cedpoilly any idea what I could do here yet?

**Comment by cedpoilly** [comment]
@everttrollip can you build a JSFiddle or a CodePen to reproduce the error?

**Comment by everttrollip** [comment]
@cedpoilly it's a bit hard since I can't use my secret client ID in the template. Do you have a starter template which I can use, to show you where it happens for me? 

Or how would you suggest I tackle this?

**Comment by everttrollip** [comment]
In the file webpack:///./node_modules/vue-gapi/dist/vue-gapi.common.js?15fd, I can see the following code causing my error: 

`
      login: function (res) {
        return Vue.prototype.$gapi.getGapiClient()
                  .then(function () {
                    login().then(function () { res(); });
                  })
`

The error in console is: 

`
vue-gapi.common.js?15fd:328 Uncaught (in promise) TypeError: res is not a function
    at eval (vue-gapi.common.js?15fd:328)
`

**Comment by cedpoilly** [comment]
@everttrollip could you create another client secret? A temporary one?

**Comment by cedpoilly** [comment]
@everttrollip Checking on this issue. Have you found a solution yet? Or do you still need help?

**Comment by everttrollip** [comment]
@cedpoilly thanks for checking in. 

I used a callback function in the login and logout method parameters, which is then called when the login/logout was successful. Did you mean for the `res` arg to be a function?
