### ISSUE TITLE
Load Gapi.js via Google CDN

### ISSUE THREAD

**Issue by andrewpeters9** [cedpoilly/vue-gapi#4]
Loading a static version of gapi.js seems to be causing some issues for this package right now - i.e., JS-blocking 404s.

Let me know if you want me to create a PR.

**Comment by hkd987** [comment]
I'm seeing the same error after working with the Admin SDK for weeks on a project I now get a 404 error and can not load the following URL

https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en_GB.Xuul3ImcGWk.O/m=auth2,client/rt=j/sv=1/d=1/ed=1/am=QQE/rs=AGLTcCNY5BLhsHJjf4ALqX2owlgNmMISlg/cb=gapi.loaded_0

**Comment by andrewpeters9** [comment]
@hkd987 If you're after a temp fix, this is the new gapi.js file you'll want to use: https://apis.google.com/js/gapi.js

Just copy and paste this wherever the old gapi.js is being used.

**Comment by hkd987** [comment]
I replace both the gapi.js file export const with the link provided & replaced the gapi var inside the vue-gapi.js This didn't seem to work.

**Comment by hkd987** [comment]
Also after making that change it throws the 404 error out twice...

**Comment by tleite** [comment]
u might wanna try this:

https://github.com/guruahn/vue-google-oauth2

**Comment by hkd987** [comment]
Was able to fix this issue by using async defer and loading the gapi api in a script tag in the head.

**Comment by hkd987** [comment]
<script src="https://apis.google.com/js/platform.js?onload=onLoadCallback" async defer></script>

**Comment by andrewpeters9** [comment]
@hkd987 Currently on my phone right now. Glad to hear you fixed it, but if you want to delegate the fix to npm then make sure the dist folders are using the new gapi.js file.

**Comment by cedpoilly** [comment]
@hkd987 @andrewpeters9 @tleite @fraunos Kindly run `npm install --save-dev  vue-gapi@latest` and let me know if the issues are now fixed.

**Comment by andrewpeters9** [comment]
@cedpoilly Works for me. Thanks.

**Comment by hkd987** [comment]
Thanks this works, had to remove all the node models folder and reinstall but Great Job!!!

much better soultion
