### ISSUE TITLE
Update the dev & build setup

### ISSUE THREAD

**Issue by cedpoilly** [cedpoilly/vue-gapi#43]
The goal is to update the setup to use modern features and improve the system overall.

**Comment by fibigerg** [comment]
The master branch is not working as a npm depency now, most likely because of mising dist folder and wrong path to it in `package.json` file. In the context of this issue https://github.com/cedpoilly/vue-gapi/issues/45 its critical to fix it ASAP. Thanks.

**Comment by cedpoilly** [comment]
@fibigerg I have pushed the /dist folder to master. Does it fix the issue for now?
We should discuss this further

**Comment by fibigerg** [comment]
Hi, yes, it works now. Thanks.

**Comment by cedpoilly** [comment]
Closing
