### ISSUE TITLE
Access token cannot be accessed in latest chrome update

### ISSUE THREAD

**Issue by everttrollip** [cedpoilly/vue-gapi#45]
It seems that Google has changed the name of the property that holds the object with the access_token from Zi to uc.

So, in the following code snippet, `authResult` is undefined. 

```
GoogleAuthService.prototype._setSession = function _setSession (response) {
  var profile = this.authInstance.currentUser.get().getBasicProfile();
  var authResult = response.Zi;
  this._setStorage(authResult, profile);
  this.authenticated = true;
};
```

Is anyone else experiencing this too?

**Comment by everttrollip** [comment]
I see there is an open pull request, #44, to replace the hardcoded Zi. I like this idea, any idea if we could implement this?

**Comment by cedpoilly** [comment]
PR merged. Will deploy this weekend ✌️

**Comment by fibigerg** [comment]
Hi, could you please push a new tag including this fix? Thanks!
