### ISSUE TITLE
Security potential issues ⚠️

### ISSUE THREAD

**Issue by DanielJaramillo94** [cedpoilly/vue-gapi#46]
Hi,

I noticed this package strongly relies on local storage, wich can lead to serious security issues.

I think you guys should check this
https://www.rdegges.com/2018/please-stop-using-local-storage/

Cheers.

**Comment by cedpoilly** [comment]
@DanielJaramillo94 
Thanks. Feel free to create a PR with a suggested solution

**Comment by DanielJaramillo94** [comment]
I'm closing this issue because the mentioned article, after further research, seems to be more like an opinion than an absolute true. Sorry for troubles.
