### ISSUE TITLE
How check if user is Authenticated to redirect him.

### ISSUE THREAD

**Issue by Robert-Dawidowski** [cedpoilly/vue-gapi#47]
@cedpoilly Hey mate,
How can I check is user is Authenticated? when I call **this.$gapi.login()** I have modal where I can select user etc. but after choose this I don't have promise to use .then(). So how can I check if user logged in correct to redirect him to some requiresAuth page.

**Comment by cedpoilly** [comment]
@Robert-Dawidowski 
Please try the following:
`const isSignedIn = await this.$getGapiClient().getAuthInstance().isSignedIn.get()`

**Comment by SamuelBonilla** [comment]
try with

```
   mounted () {
       this.$gapi.getGapiClient().then(gapi => {
          // gapi.sheets.spreadsheet.get(...)
          // ...
         gapi.auth2.getAuthInstance().isSignedIn.listen(this.updateSigninStatus)
       })
  },
  methods: {
    updateSigninStatus (isSignedIn) {
      this.auth = isSignedIn
     }
  }
```

**Comment by cedpoilly** [comment]
Closing this for now. Feel free to re-open if still applies. ✌
