### ISSUE TITLE
Remove CSS dependencies, build references

### ISSUE THREAD

**Issue by namoscato** [cedpoilly/vue-gapi#56]
There is no CSS in this project, so these are unnecessary.

**Comment by namoscato** [comment]
@cedpoilly, I was planning to hop on this next. Any objections?

**Comment by namoscato** [comment]
@cedpoilly, I'm working through this but am wondering if the `build:dll` script stuff is used?

https://github.com/cedpoilly/vue-gapi/blob/16e5cf082dc488b5f891244f00c70deb6a42ed9a/package.json#L18

**Comment by cedpoilly** [comment]
@namoscato that's probably a legacy from the template I used

**Comment by namoscato** [comment]
Alright gotcha, thanks! It sounds like I can remove that stuff then for simplicity 👌
