### ISSUE TITLE
Help needed for Typescript

### ISSUE THREAD

**Issue by Leo428** [cedpoilly/vue-gapi#6]
Firstly, thank you very much for this wrapper! 

I am using Vue with typescript. When I tried to import VueGAPI from "vue-gapi", typescript wants me to provide a .d.ts file. For now, I created an empty .d.ts file to just pass the compiler. Can you please generate a .d.ts file for typescript users? Thank you! 

Also, I am a little bit confused about how to use this: 
this.$getGapiClient()
VScode gives me an error that $getGapiClient does not exist on type "App". 

Thank you for helping me!

**Comment by cedpoilly** [comment]
Hi Leo,

If you have the skills for creating the declaration file, please go ahead and create a pull request. I will test & review it. When all is good I'll document it :)

Thanks a lot for using VueGAPI!

Cheers

**Comment by nguyendv** [comment]
This is what I use just to pass Typescript errors, but not particularly helpful in advance usages such as auto completion.

```
declare module 'vue-gapi' {
    import {PluginFunction} from 'vue';

    // The `install` method is called inside Vue.use() function. It's required.
    export const install: PluginFunction<{}>;

    // Add global object to Vue instance, so you can use `this.@login` etc.
    module 'vue/types/vue' {
        interface Vue {
            $logout: any,
            $login: any,
            $getGapiClient: () => Promise<any>,
            $isAuthenticated: any
        }
    }
}
```
I can make a PR if you're ok with this declaration file.

**Comment by cedpoilly** [comment]
@nguyendv Kindly open a PR as WIP so that we can advise. Thanks for your help

**Comment by fmeyertoens** [comment]
There are already type packages for [gapi ](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gapi)and [gapi.auth2](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gapi.auth2) that we can use like [ng-gapi](https://github.com/rubenCodeforges/ng-gapi) for angular does it.

**Comment by fmeyertoens** [comment]
I stumbled upon `Vue.gapiLoadClientPromise` and was wondering what the intention behind this variable is and how it can be typed. It's assigned `Promise<void>` but then it also has a `status `property.
https://github.com/cedpoilly/vue-gapi/blob/6d2e67d7baa5eed44c097c2739e0461c32a4a119/src/VueGAPI/index.js#L20-L27
