### ISSUE TITLE
Error: localStorage is not defined

### ISSUE THREAD

**Issue by idrys** [cedpoilly/vue-gapi#63]
Every time I try to use `import VueGAPI from 'vue-gapi` I get the message: "`localStorage is not defined`". 
Is this my wrong configuration or bug?

**Comment by cedpoilly** [comment]
@idrys can you please provide a sample project so I can investigate?
Also, does the error logged point to a specific line/file?

**Comment by idrys** [comment]
I think I solved the problem. The problem arises when using **nuxt js**.
The solution is to move the "VueGAPI import from 'vue-gapi'" line to the plugin folder.
In the `nuxt.config.js` file I added:
```
plugins: [
    { src: '~plugins/google.js', ssr: false },
  ],
```

in file plugin/google.js:

```
import Vue from 'vue'
import VueGAPI from 'vue-gapi'
const apiConfig = {
  apiKey: '<API-KEY>,
  clientId: '<CLIENT-ID>.apps.googleusercontent.com',
  discoveryDocs: ['https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest'],
  scope: 'https://www.googleapis.com/auth/calendar.readonly',
  refreshToken: true,
}
Vue.use(VueGAPI, apiConfig)
```

P.S.
The error will not indicate any particular line
_Thank you for your interest in the problem, best regard_s
