### ISSUE TITLE
isAuthenticated method will not work unless you refresh the page.

### ISSUE THREAD

**Issue by hkd987** [cedpoilly/vue-gapi#8]
Since the isAuthenticated method works by using localStorage you can not call the method in a SPA app unless you have had the user refresh the page.

This results in a messy action of forcing users to refresh the page. 

We should work towards finding a way to persists a isAuthenticated method.

**Comment by hkd987** [comment]
Might be able to create a Vuex import and store everything inside Vuex

https://stackoverflow.com/questions/45644171/adding-mutations-to-vuex-store-as-part-of-vue-plugin

here is an example of what might work

**Comment by hkd987** [comment]
Here is more info on putting things into VUEX

https://stackoverflow.com/questions/45644171/adding-mutations-to-vuex-store-as-part-of-vue-plugin

**Comment by hkd987** [comment]
https://gist.github.com/brianboyko/91fdfb492071e743e389d84eee002342#vuex

more reading on the topic

**Comment by cedpoilly** [comment]
It'll be good to have a way via Vuex, but we also need to cater for apps that don't include it

**Comment by hkd987** [comment]
Maybe say something like if an apps using vuex push into vuex else push to localhost?

**Comment by hkd987** [comment]
https://github.com/hkd987/Admin-Remix/tree/master/src/assets/gapi

There has to be a better way than this...maybe passing the store in an a variable to the configuration?

**Comment by cedpoilly** [comment]
Thanks. I saw the modification which seems interesting. However in your version you are importing the store from your custom code if I am not mistaken.
This will not be possible from the package, so we need a way to contact the application's `Store` without having to import it. 

A probable approach would be to create a VueX plugin to communicate with the `Store`:
https://vuex.vuejs.org/guide/plugins.html

**Comment by hkd987** [comment]
Right, so my thought is that we pass the store in the configuration, then we say if we have the store passed in run the mutation function.

**Comment by hkd987** [comment]
https://github.com/hkd987/vue-gapi/tree/gapi-isLogged-In

working on this

**Comment by hkd987** [comment]
waiting on other pull to finish first

**Comment by rcastera** [comment]
@cedpoilly @hkd987 The GAPI contains an event Listener for sign in status:

```
// Listen for sign-in state changes.
gapi.auth2.getAuthInstance().isSignedIn.listen(Vue.prototype.$getSignedInStatus);

// Handle the initial sign-in state.
Vue.prototype.$getSignedInStatus(gapi.auth2.getAuthInstance().isSignedIn.get());
```

I can't get vue to emit the event to be listened in a component. Maybe one of you could have better luck?

```
Vue.prototype.$getSignedInStatus = function (status) {
      if (status) {
        Vue.prototype.$emit('signedIn', true);
      } else {
        Vue.prototype.$emit('signedIn', false);
      }
    };
```

**Comment by rcastera** [comment]
Possibly an [event bus](https://medium.com/@andrejsabrickis/https-medium-com-andrejsabrickis-create-simple-eventbus-to-communicate-between-vue-js-components-cdc11cd59860) strategy?

**Comment by hkd987** [comment]
I think the best way to be creating the method in the global state, see link to my branch, then people can put that in its own computed property and then use it in v-if as desired. 

Not sure if a plugin can emit....I’d have to read the docs better.

**Comment by hkd987** [comment]
@cedpoilly  pull request has been made!!

**Comment by cedpoilly** [comment]
@hkd987 will be tested after we close Issue #10
