### ISSUE TITLE
Add inline component. 

### ISSUE THREAD

**Issue by hkd987** [cedpoilly/vue-gapi#9]
Having the pop up works and gets the job done with most cases, but devs should be able to select the login type weather it be inline, pop up etc....

**Comment by hkd987** [comment]
https://developers.google.com/identity/sign-in/web/reference#gapi.auth.signIn

Under signInOptions says that there is an option under ux_mode is "popup" or "redirect"

Just thinking that we should have an option to enable redirect. I believe this will push this will push the user to google sign in page and then back to the app they were on.

**Comment by hkd987** [comment]
ux_mode: 'redirect'

needs to be passed into the apiConfig object for this to work!

**Comment by cedpoilly** [comment]
Which part precisely?

**Comment by hkd987** [comment]
Something about the localhost redirect with google, I didnt have a bunch of time to look into it but all my redirect URLs are set up so I don't think its on my end.....

**Comment by cedpoilly** [comment]
Okay I'll check that this weekend
